image: ruby:alpine

variables:
  GIT_DEPTH: "2"

cache:
  key: "public"
  paths:
    - public

pages:
  script:
    - "apk add --no-cache git"
    - "if [[ $(git log --name-only -1 --format= | grep '^hosted/') ]]; then ruby specscript.rb; else echo 'Nothing to deploy as no files were changed in the hosted folder' && exit 1; fi"
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
