image: ruby:alpine

variables:
  GIT_DEPTH: "2"
  GIT_LFS_SKIP_SMUDGE: "1"

pages:
  before_script:
    - "apk add -U --no-cache git git-lfs"
  script:
    - "if [[ $(git log --name-only -1 --format= | grep '^hosted/') ]]; then git lfs pull -I 'hosted/' && ruby specscript.rb; else echo 'Nothing to deploy as no files were changed in the hosted folder' && exit 1; fi"
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
