image: ruby:alpine

variables:
  GIT_DEPTH: "1"

cache:
  key: "public"
  paths:
    - public

pages:
  script:
    - git diff --name-only master | grep '^hosted/'
      - [[ $? -eq 1 ]] || ruby specscript.rb
  artifacts:
    paths:
      - public
  only:
    - master
