image: ruby:alpine

variables:
  GIT_STRATEGY: none
  GIT_DEPTH: "1"
  GIT_LFS_SKIP_SMUDGE: "1"

pages:
  before_script:
    - "apk add -U --no-cache git git-lfs"
    - "git init"
    - "git remote add origin $CI_REPOSITORY_URL"
    - "git fetch --depth $GIT_DEPTH origin $CI_COMMIT_SHA"
    - "git checkout FETCH_HEAD"
  script:
    - "git lfs pull -I 'hosted/'"
    - "ruby specscript.rb"
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
