#!/bin/bash

remote="origin"
url="git@gitlab.com:gitlab-org/gitlab-design.git"
z40=0000000000000000000000000000000000000000

# Don't get into a "push loop"
if [ -n "${ALREADY_RAN_HOOK+set}" ]; then
	unset ALREADY_RAN_HOOK
	exit 1
fi

export ALREADY_RAN_HOOK = 1

# Install sketchtool
/Applications/Sketch.app/Contents/Resources/sketchtool/install.sh

# Get all sketch files you want to push
i=0
while read line
do
    array[ $i ]="$line"
    (( i++ ))
done < <(git log origin/master..master --name-only --pretty="format:" | sed 's/ /\\ /g' | sort | uniq | grep ".*\.sketch$")

# For each sketch file, generate "overwriting" with white background png exports and put them in their seperate like file named folder
for ((i = 0; i < ${#array[@]}; i++))
do
    if [ -f ${array[$i]} ]; then
        y=${array[$i]%.sketch}
        export DIR=${array[$i]%/*}
        sketchtool --overwriting="YES" --background="#FFFFFF" --output=${DIR}/${y##*/} export pages ${array[$i]// /\\ }
    else
        echo "file not found"
    fi
done

# If there are any images generated, commit them and again push
if [ -n "$(git status --porcelain)" ]; then
	git add .
	git commit -m "added preview images"
	git push
else
  echo "no changes"
fi

# This needs to be done far better with support for searching for image files that are not needed anymore

# End
exit 0
