#!/bin/sh
# Adds epic, issue, and merge request IDs of staged files to the commit message body
# Prefixes compact CE and EE project IDs (e.g 'ce#1337-…') with 'gitlab-' for proper references (e.g. 'gitlab-ce#1337-…')
# Does not prefix IDs that reference epics/issues/merge requests on other projects (e.g. ux-research#1337)

if [ x = x${2} ] || [ $2 = "message" ]; then
  STAGED_FILES=$(git diff --name-only --staged)
  IDS=$(echo "$STAGED_FILES" | sed -En 's/.*\/([a-z-]*[#|!|&][0-9]+).*/\1/p' | uniq | sed -E 's/(^ce[#|!].*|^ee[#|!].*)/gitlab-\1/')
    echo "\n\n$IDS" >> $1
fi